server:
  port: 8002      # 项目启动的端口号，不写默认8080
spring:
  themleaf:
    cache: false  #关闭themleaf缓存
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/atstudy_mall
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #配置静态资源位置，网站直接访问资,不修改源默认放在resources>static下
  web:
    resources:
      static-locations: classpath:/static
  #静态资源访问前缀
  #mvc:
    #static-path-pattern: /aaa/**

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 是否开启驼峰映射，默认是true
    map-underscore-to-camel-case: false
    # 开启查询日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImplo-camel-case

# PageHelper配置
pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true